on:
  push:
    branches: [master]
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: actions/cache@v4
        with:
          path: Library
          key: Library-
          restore-keys: Library-
      - name: Build Installer dll
        run: ./Assets/InstallerSource/DllBuild~/build-and-copy.sh
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ github.token }}
          testMode: EditMode
