on:
  push:
    branches: [master]
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
          submodules: recursive
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: Library-
      - name: Build Installer library
        if: false # not implemented
        run: ./building/build.sh build_rs
      - name: Build Installer dll
        run: ./building/build.sh build_dll

      - uses: game-ci/unity-test-runner@v2
        if: false # no unity test for now
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ github.token }}
          testMode: EditMode
