on:
  push:
    branches: [master]
  pull_request_target: {}
  workflow_dispatch: {}

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: recursive
      - uses: actions/cache@v2
        with:
          path: Library
          key: Library-${{ matrix.projectPath }}
          restore-keys: Library-
      - name: Check for env
        run: ls ./Assets/InstallerSource/semver.net
      - name: Build Installer dll
        run: ./Assets/InstallerSource/DllBuild~/build-and-copy.sh
      - uses: game-ci/unity-test-runner@v2
        env:
          UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
        with:
          githubToken: ${{ github.token }}
          testMode: EditMode
