on:
  workflow_dispatch:
    inputs:
      publish:
        description: "True to publish release to git, vpm. if false, this creates release asset only"
        type: boolean
        required: false
      publish-page:
        description: "True to Publish page even if publish is false"
        type: boolean
        required: false

env:
  CREATOR_PKG_ROOT: "Packages/com.anatawa12.vpm-package-auto-installer.creator"
  PKG_NAME: com.anatawa12.vpm-package-auto-installer.creator

concurrency:
  group: publish
  cancel-in-progress: true

jobs:
  create-release:
    runs-on: ubuntu-latest
    environment: ${{ inputs.publish && 'master-branch' || '' }}
    outputs:
      version: ${{ steps.update-version.outputs.version }}
    steps:
      - uses: actions/checkout@v4
        with: 
          submodules: recursive
          token: ${{ inputs.publish && secrets.MASTER_GITHUB_PAT || github.token }}
      - uses: anatawa12/something-releaser@v2
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown
      - uses: snow-actions/git-config-user@v1.0.0
      - name: Check version is Snapshot
        run: |
          if ! [[ "$(get-version)" = *-SNAPSHOT ]]; then
            echo 'VERSION IS NOT SNAPSHOT' >&2
            exit 1
          fi

      - name: Update Version Name
        id: update-version
        run: |
          set-version "$(version-unsnapshot "$(get-version)")"
          echo "VERSION=$(get-version)" >> "$GITHUB_ENV"
          echo "version=$(get-version)" >> "$GITHUB_OUTPUT"

      - name: Commit & tag version
        if: ${{ inputs.publish }}
        run: |
          git commit -am "$VERSION"
          git tag "v$VERSION"

      - name: Prepare build folder
        run: mkdir build

      - name: Build Installer dll
        run: ./Assets/InstallerSource/DllBuild~/build-and-copy.sh

      - name: Create Template unitypackage
        uses: anatawa12/sh-actions/create-unitypackage@master
        with:
          output-path: build/installer-template.unitypackage
          package-path: Assets/com.anatawa12.vpm-package-auto-installer

      - uses: actions/upload-artifact@v4
        with:
          name: installer-template
          path: build/installer-template.unitypackage

      - name: Build VPM release
        run: |
          # add to creator unity package
          cp build/installer-template.unitypackage "$CREATOR_PKG_ROOT/installer-template.unitypackage.bytes"
          cp "building/installer-template.unitypackage.bytes.meta" "$CREATOR_PKG_ROOT/"
          # create zip file
          pushd "$CREATOR_PKG_ROOT"
            zip -r "../../build/$PKG_NAME-$VERSION.zip" .
          popd

      - uses: actions/upload-artifact@v4
        with:
          name: vpm-package
          path: build/${{ env.PKG_NAME }}-${{ env.VERSION }}.zip

      - name: Build Creator rust
        run: TEMPLATE_UNITYPACKAGE_PATH="$(pwd)/build/installer-template.unitypackage" &&
          export TEMPLATE_UNITYPACKAGE_PATH &&
          cd "creator/rust" && 
          cargo build --target wasm32-unknown-unknown --release --lib
      - name: Inject wasm file to creator.mjs
        run: |
          # first, create base64 file
          SOURCE_WASM="$(pwd)/creator/rust/target/wasm32-unknown-unknown/release/vpai_creator.wasm"
          BASE64_WASM_LINE="$(pwd)/build/vpai_creator.wasm.base64.line"
          base64 "$SOURCE_WASM" | tr -d '\n' | tr -d '=' | sed 's/^/  const base64 = "/; s/$/";/' > "$BASE64_WASM_LINE"
          sed -e "/BASE64-INJECT-LINE/{ r build/vpai_creator.wasm.base64.line
          d }" creator/creator.mjs > build/creator.mjs
      - uses: actions/upload-artifact@v4
        with:
          name: installer-creator-js
          path: build/creator.mjs

      - name: Create Installer unitypackage
        shell: bash
        run: |
          # create creator installer unity package
          node build/creator.mjs building/config.json build/installer-creator.unitypackage

      - uses: actions/upload-artifact@v4
        with:
          name: installer-creator
          path: build/installer-creator.unitypackage

      - name: Publish Release
        if: ${{ inputs.publish }}
        run: |
          git push && git push origin "v$VERSION"

      - name: Create Pages folder
        shell: bash
        run: |
          tmp="build/pages"
          mkdir "$tmp"
          cp build/installer-template.unitypackage "$tmp/"
          cp creator/index.html "$tmp/"
          cp build/creator.mjs "$tmp/"

      - uses: actions/upload-artifact@v4
        with:
          name: pages-artifact
          path: build/pages/

      - name: publish release to github
        if: ${{ inputs.publish }}
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          sleep 1
          # upload release assets
          gh release create "v$VERSION" \
            "build/installer-creator.unitypackage" \
            "build/installer-template.unitypackage" \
            "build/$PKG_NAME-$VERSION.zip" \
            "$CREATOR_PKG_ROOT/package.json" \
            "build/creator.mjs" \

      - name: prepare next release & push
        if: ${{ inputs.publish }}
        run: |
          VERSION="$(version-next "$(get-version)")"
          set-version "$(version-snapshot "$VERSION")"
          git commit -am "prepare for next version: $VERSION"
          git push && git push --tags

  publish-cloudflare-workers:
    runs-on: ubuntu-latest
    if: inputs.publish
    needs: create-release
    environment: cloudflare workers
    steps:
      - uses: actions/checkout@v3
        with:
          ref: v${{ needs.create-release.outputs.version }}
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: wasm32-unknown-unknown

      - uses: actions/download-artifact@v3
        with:
          name: installer-template
          path: build

      # we cannot use cloudflare/wrangler-action because https://github.com/cloudflare/wrangler-action/issues/16
      - name: Publish to Cloudflare
        env:
          TEMPLATE_UNITYPACKAGE_PATH: ${{ github.workspace }}/build/installer-template.unitypackage
          CLOUDFLARE_API_TOKEN: ${{ secrets.CF_API_TOKEN }}
        working-directory: creator/worker
        run: |-
          npx wrangler publish

  publish-vpm:
    uses: anatawa12/vpm.anatawa12.com/.github/workflows/update-package.yml@master
    if: inputs.publish
    needs: create-release
    with:
      version: ${{ needs.create-release.outputs.version }}
      environment: vpm.anatawa12.com
    secrets:
      TOKEN: ${{ secrets.VPM_GITHUB_PAT }}

  publish-pages:
    runs-on: ubuntu-latest
    if: inputs.publish || inputs.publish-page
    needs: create-release
    steps:
      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: snow-actions/git-config-user@v1.0.0
      - uses: actions/download-artifact@v3
        with:
          name: pages-artifact
      - name: publish github pages
        shell: bash
        run: |
          git add .
          git commit -m "update"
          git push
