on:
  workflow_dispatch: {}

env:
  CREATOR_PKG_ROOT: "Packages/com.anatawa12.vpm-package-auto-installer.creator"
  PKG_NAME: com.anatawa12.vpm-package-auto-installer.creator

jobs:
  create_release:
    runs-on: ubuntu-latest
    environment:
      name: vpm.anatawa12.com
      url: https://vpm.anatawa12.com/
    steps:
      - uses: actions/checkout@v3
      - uses: anatawa12/something-releaser@v2
      - uses: snow-actions/git-config-user@v1.0.0
      - name: Check version is Snapshot
        run: |
          if ! [[ "$(get-version)" = *-SNAPSHOT ]]; then
            echo 'VERSION IS NOT SNAPSHOT' >&2
            exit 1
          fi

      - name: Update Version Name
        run: set-version "$(version-unsnapshot "$(get-version)")"

      - name: Commit & tag version
        run: |
          VERSION="$(get-version)"
          git commit -am "$VERSION"
          git tag "v$VERSION"
          echo "VERSION=$VERSION" >> $GITHUB_ENV

      - name: Prepare build folder
        run: mkdir build

      - name: Create Template unitypackage
        uses: anatawa12/sh-actions/create-unitypackage@master
        with:
          output-path: build/installer-template.unitypackage
          package-path: Assets/com.anatawa12.vpm-package-auto-installer

      - name: Build VPM release
        run: |
          # add to creator unity package
          cp build/installer-template.unitypackage "$CREATOR_PKG_ROOT/installer-template.unitypackage.bytes"
          cp "building/installer-template.unitypackage.bytes.meta" "$CREATOR_PKG_ROOT/"
          # create zip file
          pushd "$CREATOR_PKG_ROOT"
            zip -r "../../build/$PKG_NAME-$VERSION.zip" .
          popd

      - name: Create Installer unitypackage
        id: mk-pkg
        shell: bash
        run: |
          # create creator installer unity package
          export USE_LOCAL_PREBUILT=1
          node creator/creator.mjs building/config.json build/installer-creator.unitypackage

          tmp="$(mktemp -dt "$(basename $0).$$.XXXXXX")"
          cp build/installer-template.unitypackage "$tmp/"
          cp creator/index.html "$tmp/"
          cp creator/creator.mjs "$tmp/"
          gh-set-output "tmp" "$tmp"

      - name: Publish Release
        run: |
          git push && git push origin "v$VERSION"

      - name: publish release to github
        env:
          GH_TOKEN: ${{ github.token }}
        shell: bash
        run: |
          sleep 1
          # upload release assets
          gh release create "v$VERSION" \
            "build/installer-creator.unitypackage" \
            "build/installer-template.unitypackage" \
            "build/$PKG_NAME-$VERSION.zip" \
            "$CREATOR_PKG_ROOT/package.json" \
            "creator/creator.mjs" \

      - name: prepare next release & push
        run: |
          VERSION="$(version-next "$(get-version)")"
          set-version "$(version-snapshot "$VERSION")"
          git commit -am "prepare for next version: $VERSION"
          git push && git push --tags

      - name: Prepare Dispatch payload
        run: |
          echo "PAYLOAD=$(echo "{}" | jq -c \
              --arg REPO "$GITHUB_REPOSITORY" \
              --arg VERSION "$VERSION" \
              '.repository=$REPO | .version=$VERSION')" \
            >> "$GITHUB_ENV"
      - name: Dispatch vpm repo update
        uses: peter-evans/repository-dispatch@v2
        with:
          token: ${{ secrets.VPM_GITHUB_PAT }}
          repository: anatawa12/vpm.anatawa12.com
          event-type: update-package
          client-payload: ${{ env.PAYLOAD }}

      - name: remove repo
        run: rm -rf * .* || true

      - uses: actions/checkout@v3
        with:
          ref: gh-pages
      - uses: snow-actions/git-config-user@v1.0.0
      - name: publish github pages
        env:
          GH_TOKEN: ${{ github.token }}
          tmp: ${{ steps.mk-pkg.outputs.tmp }}
        shell: bash
        run: |
          cp "$tmp/"* .
          git add .
          git commit -m "update"
          git push
